- name: a:api-extractor
  description: Affects @discordjs/api-extractor.
  color: fbca04
- name: a:api-extractor-model
  description: Affects @discordjs/api-extractor-model.
  color: fbca04
- name: a:brokers
  description: Affects @discordjs/brokers.
  color: fbca04
- name: a:builders
  description: Affects @discordjs/builders.
  color: fbca04
- name: a:collection
  description: Affects @discordjs/collection.
  color: fbca04
- name: a:core
  description: Affects @discordjs/core.
  color: fbca04
- name: a:create-discord-bot
  description: Affects create-discord-bot.
  color: fbca04
- name: a:discord.js
  description: Affects discord.js.
  color: fbca04
- name: a:docgen
  description: Affects @discordjs/docgen.
  color: fbca04
- name: a:formatters
  description: Affects @discordjs/formatters.
  color: fbca04
- name: a:guide
  description: Affects @discordjs/guide.
  color: fbca04
- name: a:next
  description: Affects @discordjs/next.
  color: fbca04
- name: a:proxy
  description: Affects @discordjs/proxy.
  color: fbca04
- name: a:proxy-container
  description: Affects @discordjs/proxy-container.
  color: fbca04
- name: a:rest
  description: Affects @discordjs/rest.
  color: fbca04
- name: a:structures
  description: Affects @discordjs/structures.
  color: fbca04
- name: a:ui
  description: Affects @discordjs/ui.
  color: fbca04
- name: a:util
  description: Affects @discordjs/util.
  color: fbca04
- name: a:voice
  description: Affects @discordjs/voice.
  color: fbca04
- name: a:website
  description: Affects @discordjs/website.
  color: fbca04
- name: a:ws
  description: Affects @discordjs/ws.
  color: fbca04
- name: f:application commands
  description: Related to the application commands feature.
  color: b6b1f9
- name: f:applications
  description: Related to the applications feature.
  color: b6b1f9
- name: f:channel
  description: Related to the channel feature.
  color: b6b1f9
- name: f:guild
  description: Related to the guild feature.
  color: b6b1f9
- name: f:interactions
  description: Related to the interactions feature.
  color: b6b1f9
- name: f:invite
  description: Related to the invite feature.
  color: b6b1f9
- name: f:monetization
  description: Related to the monetization feature.
  color: b6b1f9
- name: f:poll
  description: Related to the poll feature.
  color: b6b1f9
- name: f:role connections
  description: Related to the role connections feature.
  color: b6b1f9
- name: f:stage instances
  description: Related to the stage instances feature.
  color: b6b1f9
- name: f:stickers
  description: Related to the stickers feature.
  color: b6b1f9
- name: f:threads
  description: Related to the threads feature.
  color: b6b1f9
- name: f:user
  description: Related to the user feature.
  color: b6b1f9
- name: f:voice
  description: Related to the voice feature.
  color: b6b1f9
- name: f:webhook
  description: Related to the webhook feature.
  color: b6b1f9
- name: s:major
  description: This is a major change.
  color: c10f47
- name: s:minor
  description: This is a minor change.
  color: e4f486
- name: s:patch
  description: This is a patch change.
  color: e8be8b
- name: t:backport
  color: 88aabb
- name: t:backport-candidate
  color: 0075ca
- name: t:duplicate
  color: cfd3d7
- name: t:invalid
  description: This is not related to discord.js.
  color: e4e669
- name: t:need reproduction
  color: c66037
- name: t:won't fix
  description: No work will be done towards this issue.
  color: cfd3d7
- name: blocked
  description: Generic label to stop Kodiak from merging a pull request.
  color: fc1423
- name: discord
  description: This is a Discord-related issue.
  color: 5865f2
- name: good first issue
  color: 7057ff
- name: help wanted
  color: '008672'
- name: in review
  description: This pull request is currently in review; halts Kodiak.
  color: aed5fc
