logFilters:
  # MISSING_PEER_DEPENDENCY
  - code: YN0002
    level: discard
  # FETCH_NOT_CACHED
  - code: YN0013
    level: discard
  # NODE_GYP_INJECTED
  - code: YN0032
    level: discard
  # INCOMPATIBLE_PEER_DEPENDENCY
  - code: YN0060
    level: discard

nodeLinker: node-modules

packageExtensions:
  '@storybook/core-common@*':
    dependencies:
      '@storybook/react-vite': 7.0.9

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-docker-build.cjs
    spec: 'https://github.com/Dcard/yarn-plugins/releases/latest/download/plugin-docker-build.js'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
