packages:
  - apps/*
  - packages/*
  - packages/create-discord-bot/template/**/*

allowBuilds:
  '@discordjs/opus': true
  '@tailwindcss/oxide': true
  bufferutil: true
  core-js-pure: false
  esbuild: true
  protobufjs: true
  rclone.js: true
  sharp: true
  unrs-resolver: false
  utf-8-validate: true
  workerd: true
  zlib-sync: true

autoInstallPeers: false

minimumReleaseAgeExclude:
  - '@typescript/typescript-darwin-arm64@7.1.0-dev.20261003.1'
  - '@typescript/typescript-darwin-x64@7.1.0-dev.20261003.1'
  - '@typescript/typescript-linux-arm64@7.1.0-dev.20261003.1'
  - '@typescript/typescript-linux-arm@7.1.0-dev.20261003.1'
  - '@typescript/typescript-linux-x64@7.1.0-dev.20261003.1'
  - '@typescript/typescript-win32-arm64@7.1.0-dev.20261003.1'
  - '@typescript/typescript-win32-x64@7.1.0-dev.20261003.1'
  - typescript@7.1.0-dev.20261003.1

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*@rushstack/node-core-library*'
  - '*jju*'

updateConfig:
  ignoreDependencies:
    - jsdoc-to-markdown
    - typedoc
