packages:
  - apps/*
  - packages/*
  - packages/create-discord-bot/template/**/*

allowBuilds:
  '@discordjs/opus': true
  '@tailwindcss/oxide': true
  bufferutil: true
  core-js-pure: false
  esbuild: true
  protobufjs: true
  rclone.js: true
  sharp: true
  unrs-resolver: false
  utf-8-validate: true
  workerd: true
  zlib-sync: true

autoInstallPeers: false

patchedDependencies:
  '@microsoft/tsdoc-config@0.17.1': patches/@microsoft__tsdoc-config@0.17.1.patch

peerDependencyRules:
  allowAny:
    - '*'
  ignoreMissing:
    - '*'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*@rushstack/node-core-library*'
  - '*jju*'

updateConfig:
  ignoreDependencies:
    - jsdoc-to-markdown
    - typedoc
