autoInstallPeers: false

ignoredBuiltDependencies:
  - core-js-pure

onlyBuiltDependencies:
  - '@discordjs/opus'
  - bufferutil
  - esbuild
  - protobufjs
  - sharp
  - utf-8-validate
  - zlib-sync

packages:
  - apps/*
  - packages/*

peerDependencyRules:
  ignoreMissing:
    - '*'
  allowAny:
    - '*'

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*@rushstack/node-core-library*'
  - '*jju*'

patchedDependencies:
  '@microsoft/tsdoc-config@0.16.2': patches/@microsoft__tsdoc-config@0.16.2.patch
  'zlib-sync@0.1.9': patches/zlib-sync@0.1.9.patch
