// "Root" classes (starting points)
import packageJson from '../package.json' with { type: 'json' };

export { Client } from './client/Client.js';
export { Shard } from './sharding/Shard.js';
export { ShardClientUtil } from './sharding/ShardClientUtil.js';
export { ShardingManager } from './sharding/ShardingManager.js';

// Errors
export { DiscordjsError } from './errors/DJSError.js';
export { DiscordjsTypeError } from './errors/DJSError.js';
export { DiscordjsRangeError } from './errors/DJSError.js';
export { ErrorCodes as DiscordjsErrorCodes } from './errors/ErrorCodes.js';

// Utilities
export { ActivityFlagsBitField } from './util/ActivityFlagsBitField.js';
export { ApplicationFlagsBitField } from './util/ApplicationFlagsBitField.js';
export { AttachmentFlagsBitField } from './util/AttachmentFlagsBitField.js';
export { BaseManager } from './managers/BaseManager.js';
export { BitField } from './util/BitField.js';
export { ChannelFlagsBitField } from './util/ChannelFlagsBitField.js';
export { Collection } from '@discordjs/collection';
export { Colors } from './util/Colors.js';
export * as Constants from './util/Constants.js';
export { Events } from './util/Events.js';
export { GuildMemberFlagsBitField } from './util/GuildMemberFlagsBitField.js';
export { IntentsBitField } from './util/IntentsBitField.js';
export { InviteFlagsBitField } from './util/InviteFlagsBitField.js';
export { LimitedCollection } from './util/LimitedCollection.js';
export { MessageFlagsBitField } from './util/MessageFlagsBitField.js';
export { Options } from './util/Options.js';
export { Partials } from './util/Partials.js';
export { PermissionsBitField } from './util/PermissionsBitField.js';
export { RoleFlagsBitField } from './util/RoleFlagsBitField.js';
export { ShardEvents } from './util/ShardEvents.js';
export { SKUFlagsBitField } from './util/SKUFlagsBitField.js';
export { DiscordSnowflake as SnowflakeUtil } from '@sapphire/snowflake';
export { Status } from './util/Status.js';
export { Sweepers } from './util/Sweepers.js';
export { SystemChannelFlagsBitField } from './util/SystemChannelFlagsBitField.js';
export { ThreadMemberFlagsBitField } from './util/ThreadMemberFlagsBitField.js';
export { UserFlagsBitField } from './util/UserFlagsBitField.js';

export * from './util/DataResolver.js';

export { cleanCodeBlockContent } from './util/Util.js';
export { cleanContent } from './util/Util.js';
export { discordSort } from './util/Util.js';
export { fetchRecommendedShardCount } from './util/Util.js';
export { flatten } from './util/Util.js';
export { parseEmoji } from './util/Util.js';
export { parseWebhookURL } from './util/Util.js';
export { resolveColor } from './util/Util.js';
export { resolveSKUId } from './util/Util.js';
export { verifyString } from './util/Util.js';
export const version = packageJson.version;

// Managers
export { ApplicationCommandManager } from './managers/ApplicationCommandManager.js';
export { ApplicationCommandPermissionsManager } from './managers/ApplicationCommandPermissionsManager.js';
export { ApplicationEmojiManager } from './managers/ApplicationEmojiManager.js';
export { AutoModerationRuleManager } from './managers/AutoModerationRuleManager.js';
export { CachedManager } from './managers/CachedManager.js';
export { ChannelManager } from './managers/ChannelManager.js';
export { ClientVoiceManager } from './client/voice/ClientVoiceManager.js';
export { DataManager } from './managers/DataManager.js';
export { DMMessageManager } from './managers/DMMessageManager.js';
export { EntitlementManager } from './managers/EntitlementManager.js';
export { GuildApplicationCommandManager } from './managers/GuildApplicationCommandManager.js';
export { GuildBanManager } from './managers/GuildBanManager.js';
export { GuildChannelManager } from './managers/GuildChannelManager.js';
export { GuildEmojiManager } from './managers/GuildEmojiManager.js';
export { GuildEmojiRoleManager } from './managers/GuildEmojiRoleManager.js';
export { GuildForumThreadManager } from './managers/GuildForumThreadManager.js';
export { GuildInviteManager } from './managers/GuildInviteManager.js';
export { GuildManager } from './managers/GuildManager.js';
export { GuildMemberManager } from './managers/GuildMemberManager.js';
export { GuildMemberRoleManager } from './managers/GuildMemberRoleManager.js';
export { GuildMessageManager } from './managers/GuildMessageManager.js';
export { GuildScheduledEventManager } from './managers/GuildScheduledEventManager.js';
export { GuildSoundboardSoundManager } from './managers/GuildSoundboardSoundManager.js';
export { GuildStickerManager } from './managers/GuildStickerManager.js';
export { GuildTextThreadManager } from './managers/GuildTextThreadManager.js';
export { MessageManager } from './managers/MessageManager.js';
export { PermissionOverwriteManager } from './managers/PermissionOverwriteManager.js';
export { PollAnswerVoterManager } from './managers/PollAnswerVoterManager.js';
export { PresenceManager } from './managers/PresenceManager.js';
export { ReactionManager } from './managers/ReactionManager.js';
export { ReactionUserManager } from './managers/ReactionUserManager.js';
export { RoleManager } from './managers/RoleManager.js';
export { StageInstanceManager } from './managers/StageInstanceManager.js';
export { SubscriptionManager } from './managers/SubscriptionManager.js';
export { ThreadManager } from './managers/ThreadManager.js';
export { ThreadMemberManager } from './managers/ThreadMemberManager.js';
export { UserManager } from './managers/UserManager.js';
export { VoiceStateManager } from './managers/VoiceStateManager.js';

// Structures
export { ActionRow } from './structures/ActionRow.js';
export { Activity } from './structures/Presence.js';
export { ActivityInstance } from './structures/ActivityInstance.js';
export { ActivityLocation } from './structures/ActivityLocation.js';
export { AnnouncementChannel } from './structures/AnnouncementChannel.js';
export { AnonymousGuild } from './structures/AnonymousGuild.js';
export { AuthorizingIntegrationOwners } from './structures/AuthorizingIntegrationOwners.js';
export { Application } from './structures/interfaces/Application.js';
export { ApplicationCommand } from './structures/ApplicationCommand.js';
export { ApplicationEmoji } from './structures/ApplicationEmoji.js';
export { ApplicationRoleConnectionMetadata } from './structures/ApplicationRoleConnectionMetadata.js';
export { Attachment } from './structures/Attachment.js';
export { AutocompleteInteraction } from './structures/AutocompleteInteraction.js';
export { AutoModerationActionExecution } from './structures/AutoModerationActionExecution.js';
export { AutoModerationRule } from './structures/AutoModerationRule.js';
export { Base } from './structures/Base.js';
export { BaseChannel } from './structures/BaseChannel.js';
export { BaseGuild } from './structures/BaseGuild.js';
export { BaseGuildEmoji } from './structures/BaseGuildEmoji.js';
export { BaseGuildTextChannel } from './structures/BaseGuildTextChannel.js';
export { BaseGuildVoiceChannel } from './structures/BaseGuildVoiceChannel.js';
export { BaseInteraction } from './structures/BaseInteraction.js';
export { BaseInvite } from './structures/BaseInvite.js';
export { BaseSelectMenuComponent } from './structures/BaseSelectMenuComponent.js';
export { ButtonComponent } from './structures/ButtonComponent.js';
export { ButtonInteraction } from './structures/ButtonInteraction.js';
export { CategoryChannel } from './structures/CategoryChannel.js';
export { ChannelSelectMenuComponent } from './structures/ChannelSelectMenuComponent.js';
export { ChannelSelectMenuInteraction } from './structures/ChannelSelectMenuInteraction.js';
export { ChatInputCommandInteraction } from './structures/ChatInputCommandInteraction.js';
export { ClientApplication } from './structures/ClientApplication.js';
export { ClientPresence } from './structures/ClientPresence.js';
export { ClientUser } from './structures/ClientUser.js';
export { Collector } from './structures/interfaces/Collector.js';
export { CommandInteraction } from './structures/CommandInteraction.js';
export { CommandInteractionOptionResolver } from './structures/CommandInteractionOptionResolver.js';
export { Component } from './structures/Component.js';
export { ContainerComponent } from './structures/ContainerComponent.js';
export { ContextMenuCommandInteraction } from './structures/ContextMenuCommandInteraction.js';
export { DirectoryChannel } from './structures/DirectoryChannel.js';
export { DMChannel } from './structures/DMChannel.js';
export { Embed } from './structures/Embed.js';
export { Emoji } from './structures/Emoji.js';
export { Entitlement } from './structures/Entitlement.js';
export { FileComponent } from './structures/FileComponent.js';
export { ForumChannel } from './structures/ForumChannel.js';
export { GroupDMInvite } from './structures/GroupDMInvite.js';
export { Guild } from './structures/Guild.js';
export { GuildAuditLogs } from './structures/GuildAuditLogs.js';
export { GuildAuditLogsEntry } from './structures/GuildAuditLogsEntry.js';
export { GuildBan } from './structures/GuildBan.js';
export { GuildChannel } from './structures/GuildChannel.js';
export { GuildEmoji } from './structures/GuildEmoji.js';
export { GuildInvite } from './structures/GuildInvite.js';
export { GuildMember } from './structures/GuildMember.js';
export { GuildOnboarding } from './structures/GuildOnboarding.js';
export { GuildOnboardingPrompt } from './structures/GuildOnboardingPrompt.js';
export { GuildOnboardingPromptOption } from './structures/GuildOnboardingPromptOption.js';
export { GuildPreview } from './structures/GuildPreview.js';
export { GuildPreviewEmoji } from './structures/GuildPreviewEmoji.js';
export { GuildScheduledEvent } from './structures/GuildScheduledEvent.js';
export { GuildTemplate } from './structures/GuildTemplate.js';
export { Integration } from './structures/Integration.js';
export { IntegrationApplication } from './structures/IntegrationApplication.js';
export { InteractionCallback } from './structures/InteractionCallback.js';
export { InteractionCallbackResource } from './structures/InteractionCallbackResource.js';
export { InteractionCallbackResponse } from './structures/InteractionCallbackResponse.js';
export { InteractionCollector } from './structures/InteractionCollector.js';
export { InteractionWebhook } from './structures/InteractionWebhook.js';
export { InviteGuild } from './structures/InviteGuild.js';
export { LabelComponent } from './structures/LabelComponent.js';
export { MediaChannel } from './structures/MediaChannel.js';
export { MediaGalleryComponent } from './structures/MediaGalleryComponent.js';
export { MediaGalleryItem } from './structures/MediaGalleryItem.js';
export { MentionableSelectMenuComponent } from './structures/MentionableSelectMenuComponent.js';
export { MentionableSelectMenuInteraction } from './structures/MentionableSelectMenuInteraction.js';
export { Message } from './structures/Message.js';
export { MessageCollector } from './structures/MessageCollector.js';
export { MessageComponentInteraction } from './structures/MessageComponentInteraction.js';
export { MessageContextMenuCommandInteraction } from './structures/MessageContextMenuCommandInteraction.js';
export { MessageMentions } from './structures/MessageMentions.js';
export { MessagePayload } from './structures/MessagePayload.js';
export { MessageReaction } from './structures/MessageReaction.js';
export { ModalComponentResolver } from './structures/ModalComponentResolver.js';
export { ModalSubmitInteraction } from './structures/ModalSubmitInteraction.js';
export { OAuth2Guild } from './structures/OAuth2Guild.js';
export { PartialGroupDMChannel } from './structures/PartialGroupDMChannel.js';
export { PermissionOverwrites } from './structures/PermissionOverwrites.js';
export { Poll } from './structures/Poll.js';
export { PollAnswer } from './structures/PollAnswer.js';
export { PrimaryEntryPointCommandInteraction } from './structures/PrimaryEntryPointCommandInteraction.js';
export { Presence } from './structures/Presence.js';
export { ReactionCollector } from './structures/ReactionCollector.js';
export { ReactionEmoji } from './structures/ReactionEmoji.js';
export { RichPresenceAssets } from './structures/Presence.js';
export { Role } from './structures/Role.js';
export { RoleSelectMenuComponent } from './structures/RoleSelectMenuComponent.js';
export { RoleSelectMenuInteraction } from './structures/RoleSelectMenuInteraction.js';
export { SectionComponent } from './structures/SectionComponent.js';
export { SeparatorComponent } from './structures/SeparatorComponent.js';
export { SKU } from './structures/SKU.js';
export { SoundboardSound } from './structures/SoundboardSound.js';
export { StageChannel } from './structures/StageChannel.js';
export { StageInstance } from './structures/StageInstance.js';
export { Sticker } from './structures/Sticker.js';
export { StickerPack } from './structures/StickerPack.js';
export { StringSelectMenuComponent } from './structures/StringSelectMenuComponent.js';
export { StringSelectMenuInteraction } from './structures/StringSelectMenuInteraction.js';
export { Subscription } from './structures/Subscription.js';
export { Team } from './structures/Team.js';
export { TeamMember } from './structures/TeamMember.js';
export { TextChannel } from './structures/TextChannel.js';
export { TextDisplayComponent } from './structures/TextDisplayComponent.js';
export { TextInputComponent } from './structures/TextInputComponent.js';
export { ThreadChannel } from './structures/ThreadChannel.js';
export { ThreadMember } from './structures/ThreadMember.js';
export { ThreadOnlyChannel } from './structures/ThreadOnlyChannel.js';
export { ThumbnailComponent } from './structures/ThumbnailComponent.js';
export { Typing } from './structures/Typing.js';
export { UnfurledMediaItem } from './structures/UnfurledMediaItem.js';
export { User } from './structures/User.js';
export { UserContextMenuCommandInteraction } from './structures/UserContextMenuCommandInteraction.js';
export { UserSelectMenuComponent } from './structures/UserSelectMenuComponent.js';
export { UserSelectMenuInteraction } from './structures/UserSelectMenuInteraction.js';
export { VoiceChannel } from './structures/VoiceChannel.js';
export { VoiceChannelEffect } from './structures/VoiceChannelEffect.js';
export { VoiceRegion } from './structures/VoiceRegion.js';
export { VoiceState } from './structures/VoiceState.js';
export { Webhook } from './structures/Webhook.js';
export { WelcomeChannel } from './structures/WelcomeChannel.js';
export { WelcomeScreen } from './structures/WelcomeScreen.js';
export { Widget } from './structures/Widget.js';
export { WidgetMember } from './structures/WidgetMember.js';

// External
export * from 'discord-api-types/v10';
export * from '@discordjs/rest';
export * from '@discordjs/util';
export * from '@discordjs/ws';
