'use strict';

const { createEnum } = require('../util/Enums');

module.exports = createEnum([
  'CLIENT_INVALID_OPTION',
  'CLIENT_INVALID_PROVIDED_SHARDS',
  'CLIENT_MISSING_INTENTS',
  'CLIENT_NOT_READY',

  'TOKEN_INVALID',
  'TOKEN_MISSING',
  'APPLICATION_COMMAND_PERMISSIONS_TOKEN_MISSING',

  'WS_CLOSE_REQUESTED',
  'WS_CONNECTION_EXISTS',
  'WS_NOT_OPEN',
  'MANAGER_DESTROYED',

  'BITFIELD_INVALID',

  'SHARDING_INVALID',
  'SHARDING_REQUIRED',
  'INVALID_INTENTS',
  'DISALLOWED_INTENTS',
  'SHARDING_NO_SHARDS',
  'SHARDING_IN_PROCESS',
  'SHARDING_INVALID_EVAL_BROADCAST',
  'SHARDING_SHARD_NOT_FOUND',
  'SHARDING_ALREADY_SPAWNED',
  'SHARDING_PROCESS_EXISTS',
  'SHARDING_WORKER_EXISTS',
  'SHARDING_READY_TIMEOUT',
  'SHARDING_READY_DISCONNECTED',
  'SHARDING_READY_DIED',
  'SHARDING_NO_CHILD_EXISTS',
  'SHARDING_SHARD_MISCALCULATION',

  'COLOR_RANGE',
  'COLOR_CONVERT',

  'INVITE_OPTIONS_MISSING_CHANNEL',

  'BUTTON_LABEL',
  'BUTTON_URL',
  'BUTTON_CUSTOM_ID',

  'SELECT_MENU_CUSTOM_ID',
  'SELECT_MENU_PLACEHOLDER',
  'SELECT_OPTION_LABEL',
  'SELECT_OPTION_VALUE',
  'SELECT_OPTION_DESCRIPTION',

  'INTERACTION_COLLECTOR_ERROR',

  'FILE_NOT_FOUND',

  'USER_BANNER_NOT_FETCHED',
  'USER_NO_DM_CHANNEL',

  'VOICE_NOT_STAGE_CHANNEL',

  'VOICE_STATE_NOT_OWN',
  'VOICE_STATE_INVALID_TYPE',

  'REQ_RESOURCE_TYPE',

  'IMAGE_FORMAT',
  'IMAGE_SIZE',

  'MESSAGE_BULK_DELETE_TYPE',
  'MESSAGE_NONCE_TYPE',
  'MESSAGE_CONTENT_TYPE',

  'SPLIT_MAX_LEN',

  'BAN_RESOLVE_ID',
  'FETCH_BAN_RESOLVE_ID',

  'PRUNE_DAYS_TYPE',

  'GUILD_CHANNEL_RESOLVE',
  'GUILD_VOICE_CHANNEL_RESOLVE',
  'GUILD_CHANNEL_ORPHAN',
  'GUILD_CHANNEL_UNOWNED',
  'GUILD_OWNED',
  'GUILD_MEMBERS_TIMEOUT',
  'GUILD_UNCACHED_ME',
  'CHANNEL_NOT_CACHED',
  'STAGE_CHANNEL_RESOLVE',
  'GUILD_SCHEDULED_EVENT_RESOLVE',
  'FETCH_OWNER_ID',

  'INVALID_TYPE',
  'INVALID_ELEMENT',

  'MESSAGE_THREAD_PARENT',
  'MESSAGE_EXISTING_THREAD',
  'THREAD_INVITABLE_TYPE',

  'WEBHOOK_MESSAGE',
  'WEBHOOK_TOKEN_UNAVAILABLE',
  'WEBHOOK_URL_INVALID',
  'WEBHOOK_APPLICATION',
  'MESSAGE_REFERENCE_MISSING',

  'EMOJI_TYPE',
  'EMOJI_MANAGED',
  'MISSING_MANAGE_EMOJIS_AND_STICKERS_PERMISSION',
  'NOT_GUILD_STICKER',

  'REACTION_RESOLVE_USER',

  'VANITY_URL',

  'INVITE_RESOLVE_CODE',

  'INVITE_NOT_FOUND',

  'DELETE_GROUP_DM_CHANNEL',
  'FETCH_GROUP_DM_CHANNEL',

  'MEMBER_FETCH_NONCE_LENGTH',

  'GLOBAL_COMMAND_PERMISSIONS',
  'GUILD_UNCACHED_ENTITY_RESOLVE',

  'INTERACTION_ALREADY_REPLIED',
  'INTERACTION_NOT_REPLIED',
  'INTERACTION_EPHEMERAL_REPLIED',

  'COMMAND_INTERACTION_OPTION_NOT_FOUND',
  'COMMAND_INTERACTION_OPTION_TYPE',
  'COMMAND_INTERACTION_OPTION_NO_SUB_COMMAND',
  'COMMAND_INTERACTION_OPTION_NO_SUB_COMMAND_GROUP',
  'AUTOCOMPLETE_INTERACTION_OPTION_NO_FOCUSED_OPTION',

  'MODAL_SUBMIT_INTERACTION_FIELD_NOT_FOUND',
  'MODAL_SUBMIT_INTERACTION_FIELD_TYPE',

  'INVITE_MISSING_SCOPES',

  'NOT_IMPLEMENTED',

  'SWEEP_FILTER_RETURN',
]);
