"use strict"; /**
 * Object containing user agent data required for API requests.
 * @typedef {(object)} UserAgent
 * @property {string} [url=https://github.com/hydrabolt/discord.js] URL to the repository/homepage of the creator.
 * @property {string} [version=6.0.0] version of your bot.
 * @property {string} full stringified user-agent that is generate automatically upon changes. Read-only.
*/ /**
 * Object containing properties that can be used to alter the client's functionality.
 * @typedef {(object)} ClientOptions
 * @property {boolean} [compress=true] whether or not large packets that are sent over WebSockets should be compressed.
 * @property {boolean} [autoReconnect=false] whether the Client should attempt to automatically reconnect if it is disconnected.
 * @property {boolean} [rateLimitAsError=false] whether rejections to API requests due to rate-limiting should be treated as errors.
 * @property {Number} [largeThreshold=250] an integer between 0 and 250. When a server has more users than `options.largeThreshold`, only the online/active users are cached.
*/ /**
 * Object containing properties that will be applied when deleting messages
 * @typedef {(object)} MessageDeletionOptions
 * @property {Number} [wait] If set, the message will be deleted after `options.wait` milliseconds.
 */ /**
 * Object containing properties that will be used when fetching channel logs. You cannot specify _both_ `options.before` and `options.after`
 * @typedef {(object)} ChannelLogsOptions
 * @property {MessageResolvable} [before] When fetching logs, it will fetch from messages before `options.before` but not including it.
 * @property {MessageResolvable} [after] When fetching logs, it will fetch from messages after `options.after` but not including it.
 */exports.__esModule = true;function _interopRequireDefault(obj){return obj && obj.__esModule?obj:{"default":obj};}var _ClientClient=require("./Client/Client");var _ClientClient2=_interopRequireDefault(_ClientClient);var _StructuresChannel=require("./Structures/Channel");var _StructuresChannel2=_interopRequireDefault(_StructuresChannel);var _StructuresChannelPermissions=require("./Structures/ChannelPermissions");var _StructuresChannelPermissions2=_interopRequireDefault(_StructuresChannelPermissions);var _StructuresInvite=require("./Structures/Invite");var _StructuresInvite2=_interopRequireDefault(_StructuresInvite);var _StructuresMessage=require("./Structures/Message");var _StructuresMessage2=_interopRequireDefault(_StructuresMessage);var _StructuresPermissionOverwrite=require("./Structures/PermissionOverwrite");var _StructuresPermissionOverwrite2=_interopRequireDefault(_StructuresPermissionOverwrite);var _StructuresPMChannel=require("./Structures/PMChannel");var _StructuresPMChannel2=_interopRequireDefault(_StructuresPMChannel);var _StructuresRole=require("./Structures/Role");var _StructuresRole2=_interopRequireDefault(_StructuresRole);var _StructuresServer=require("./Structures/Server");var _StructuresServer2=_interopRequireDefault(_StructuresServer);var _StructuresServerChannel=require("./Structures/ServerChannel");var _StructuresServerChannel2=_interopRequireDefault(_StructuresServerChannel);var _StructuresTextChannel=require("./Structures/TextChannel");var _StructuresTextChannel2=_interopRequireDefault(_StructuresTextChannel);var _StructuresUser=require("./Structures/User");var _StructuresUser2=_interopRequireDefault(_StructuresUser);var _StructuresVoiceChannel=require("./Structures/VoiceChannel");var _StructuresVoiceChannel2=_interopRequireDefault(_StructuresVoiceChannel);var _StructuresWebhook=require("./Structures/Webhook");var _StructuresWebhook2=_interopRequireDefault(_StructuresWebhook);var _Constants=require("./Constants");var _Constants2=_interopRequireDefault(_Constants);var _UtilCacheJs=require("./Util/Cache.js");var _UtilCacheJs2=_interopRequireDefault(_UtilCacheJs);exports["default"] = {Client:_ClientClient2["default"],Channel:_StructuresChannel2["default"],ChannelPermissions:_StructuresChannelPermissions2["default"],Invite:_StructuresInvite2["default"],Message:_StructuresMessage2["default"],PermissionOverwrite:_StructuresPermissionOverwrite2["default"],PMChannel:_StructuresPMChannel2["default"],Role:_StructuresRole2["default"],Server:_StructuresServer2["default"],ServerChannel:_StructuresServerChannel2["default"],TextChannel:_StructuresTextChannel2["default"],User:_StructuresUser2["default"],VoiceChannel:_StructuresVoiceChannel2["default"],Webhook:_StructuresWebhook2["default"],Constants:_Constants2["default"],Cache:_UtilCacheJs2["default"]};module.exports = exports["default"];
