import APPLICATION_COMMAND_PERMISSIONS_UPDATE from './APPLICATION_COMMAND_PERMISSIONS_UPDATE.js';
import AUTO_MODERATION_ACTION_EXECUTION from './AUTO_MODERATION_ACTION_EXECUTION.js';
import AUTO_MODERATION_RULE_CREATE from './AUTO_MODERATION_RULE_CREATE.js';
import AUTO_MODERATION_RULE_DELETE from './AUTO_MODERATION_RULE_DELETE.js';
import AUTO_MODERATION_RULE_UPDATE from './AUTO_MODERATION_RULE_UPDATE.js';
import CHANNEL_CREATE from './CHANNEL_CREATE.js';
import CHANNEL_DELETE from './CHANNEL_DELETE.js';
import CHANNEL_PINS_UPDATE from './CHANNEL_PINS_UPDATE.js';
import CHANNEL_UPDATE from './CHANNEL_UPDATE.js';
import ENTITLEMENT_CREATE from './ENTITLEMENT_CREATE.js';
import ENTITLEMENT_DELETE from './ENTITLEMENT_DELETE.js';
import ENTITLEMENT_UPDATE from './ENTITLEMENT_UPDATE.js';
import GUILD_AUDIT_LOG_ENTRY_CREATE from './GUILD_AUDIT_LOG_ENTRY_CREATE.js';
import GUILD_BAN_ADD from './GUILD_BAN_ADD.js';
import GUILD_BAN_REMOVE from './GUILD_BAN_REMOVE.js';
import GUILD_CREATE from './GUILD_CREATE.js';
import GUILD_DELETE from './GUILD_DELETE.js';
import GUILD_EMOJIS_UPDATE from './GUILD_EMOJIS_UPDATE.js';
import GUILD_INTEGRATIONS_UPDATE from './GUILD_INTEGRATIONS_UPDATE.js';
import GUILD_MEMBERS_CHUNK from './GUILD_MEMBERS_CHUNK.js';
import GUILD_MEMBER_ADD from './GUILD_MEMBER_ADD.js';
import GUILD_MEMBER_REMOVE from './GUILD_MEMBER_REMOVE.js';
import GUILD_MEMBER_UPDATE from './GUILD_MEMBER_UPDATE.js';
import GUILD_ROLE_CREATE from './GUILD_ROLE_CREATE.js';
import GUILD_ROLE_DELETE from './GUILD_ROLE_DELETE.js';
import GUILD_ROLE_UPDATE from './GUILD_ROLE_UPDATE.js';
import GUILD_SCHEDULED_EVENT_CREATE from './GUILD_SCHEDULED_EVENT_CREATE.js';
import GUILD_SCHEDULED_EVENT_DELETE from './GUILD_SCHEDULED_EVENT_DELETE.js';
import GUILD_SCHEDULED_EVENT_UPDATE from './GUILD_SCHEDULED_EVENT_UPDATE.js';
import GUILD_SCHEDULED_EVENT_USER_ADD from './GUILD_SCHEDULED_EVENT_USER_ADD.js';
import GUILD_SCHEDULED_EVENT_USER_REMOVE from './GUILD_SCHEDULED_EVENT_USER_REMOVE.js';
import GUILD_SOUNDBOARD_SOUNDS_UPDATE from './GUILD_SOUNDBOARD_SOUNDS_UPDATE.js';
import GUILD_SOUNDBOARD_SOUND_CREATE from './GUILD_SOUNDBOARD_SOUND_CREATE.js';
import GUILD_SOUNDBOARD_SOUND_DELETE from './GUILD_SOUNDBOARD_SOUND_DELETE.js';
import GUILD_SOUNDBOARD_SOUND_UPDATE from './GUILD_SOUNDBOARD_SOUND_UPDATE.js';
import GUILD_STICKERS_UPDATE from './GUILD_STICKERS_UPDATE.js';
import GUILD_UPDATE from './GUILD_UPDATE.js';
import INTERACTION_CREATE from './INTERACTION_CREATE.js';
import INVITE_CREATE from './INVITE_CREATE.js';
import INVITE_DELETE from './INVITE_DELETE.js';
import MESSAGE_CREATE from './MESSAGE_CREATE.js';
import MESSAGE_DELETE from './MESSAGE_DELETE.js';
import MESSAGE_DELETE_BULK from './MESSAGE_DELETE_BULK.js';
import MESSAGE_POLL_VOTE_ADD from './MESSAGE_POLL_VOTE_ADD.js';
import MESSAGE_POLL_VOTE_REMOVE from './MESSAGE_POLL_VOTE_REMOVE.js';
import MESSAGE_REACTION_ADD from './MESSAGE_REACTION_ADD.js';
import MESSAGE_REACTION_REMOVE from './MESSAGE_REACTION_REMOVE.js';
import MESSAGE_REACTION_REMOVE_ALL from './MESSAGE_REACTION_REMOVE_ALL.js';
import MESSAGE_REACTION_REMOVE_EMOJI from './MESSAGE_REACTION_REMOVE_EMOJI.js';
import MESSAGE_UPDATE from './MESSAGE_UPDATE.js';
import PRESENCE_UPDATE from './PRESENCE_UPDATE.js';
import RATE_LIMITED from './RATE_LIMITED.js';
import READY from './READY.js';
import SOUNDBOARD_SOUNDS from './SOUNDBOARD_SOUNDS.js';
import STAGE_INSTANCE_CREATE from './STAGE_INSTANCE_CREATE.js';
import STAGE_INSTANCE_DELETE from './STAGE_INSTANCE_DELETE.js';
import STAGE_INSTANCE_UPDATE from './STAGE_INSTANCE_UPDATE.js';
import SUBSCRIPTION_CREATE from './SUBSCRIPTION_CREATE.js';
import SUBSCRIPTION_DELETE from './SUBSCRIPTION_DELETE.js';
import SUBSCRIPTION_UPDATE from './SUBSCRIPTION_UPDATE.js';
import THREAD_CREATE from './THREAD_CREATE.js';
import THREAD_DELETE from './THREAD_DELETE.js';
import THREAD_LIST_SYNC from './THREAD_LIST_SYNC.js';
import THREAD_MEMBERS_UPDATE from './THREAD_MEMBERS_UPDATE.js';
import THREAD_MEMBER_UPDATE from './THREAD_MEMBER_UPDATE.js';
import THREAD_UPDATE from './THREAD_UPDATE.js';
import TYPING_START from './TYPING_START.js';
import USER_UPDATE from './USER_UPDATE.js';
import VOICE_CHANNEL_EFFECT_SEND from './VOICE_CHANNEL_EFFECT_SEND.js';
import VOICE_SERVER_UPDATE from './VOICE_SERVER_UPDATE.js';
import VOICE_STATE_UPDATE from './VOICE_STATE_UPDATE.js';
import WEBHOOKS_UPDATE from './WEBHOOKS_UPDATE.js';

export const PacketHandlers = {
  APPLICATION_COMMAND_PERMISSIONS_UPDATE,
  AUTO_MODERATION_ACTION_EXECUTION,
  AUTO_MODERATION_RULE_CREATE,
  AUTO_MODERATION_RULE_DELETE,
  AUTO_MODERATION_RULE_UPDATE,
  CHANNEL_CREATE,
  CHANNEL_DELETE,
  CHANNEL_PINS_UPDATE,
  CHANNEL_UPDATE,
  ENTITLEMENT_CREATE,
  ENTITLEMENT_DELETE,
  ENTITLEMENT_UPDATE,
  GUILD_AUDIT_LOG_ENTRY_CREATE,
  GUILD_BAN_ADD,
  GUILD_BAN_REMOVE,
  GUILD_CREATE,
  GUILD_DELETE,
  GUILD_EMOJIS_UPDATE,
  GUILD_INTEGRATIONS_UPDATE,
  GUILD_MEMBERS_CHUNK,
  GUILD_MEMBER_ADD,
  GUILD_MEMBER_REMOVE,
  GUILD_MEMBER_UPDATE,
  GUILD_ROLE_CREATE,
  GUILD_ROLE_DELETE,
  GUILD_ROLE_UPDATE,
  GUILD_SCHEDULED_EVENT_CREATE,
  GUILD_SCHEDULED_EVENT_DELETE,
  GUILD_SCHEDULED_EVENT_UPDATE,
  GUILD_SCHEDULED_EVENT_USER_ADD,
  GUILD_SCHEDULED_EVENT_USER_REMOVE,
  GUILD_SOUNDBOARD_SOUNDS_UPDATE,
  GUILD_SOUNDBOARD_SOUND_CREATE,
  GUILD_SOUNDBOARD_SOUND_DELETE,
  GUILD_SOUNDBOARD_SOUND_UPDATE,
  GUILD_STICKERS_UPDATE,
  GUILD_UPDATE,
  INTERACTION_CREATE,
  INVITE_CREATE,
  INVITE_DELETE,
  MESSAGE_CREATE,
  MESSAGE_DELETE,
  MESSAGE_DELETE_BULK,
  MESSAGE_POLL_VOTE_ADD,
  MESSAGE_POLL_VOTE_REMOVE,
  MESSAGE_REACTION_ADD,
  MESSAGE_REACTION_REMOVE,
  MESSAGE_REACTION_REMOVE_ALL,
  MESSAGE_REACTION_REMOVE_EMOJI,
  MESSAGE_UPDATE,
  PRESENCE_UPDATE,
  RATE_LIMITED,
  READY,
  SOUNDBOARD_SOUNDS,
  STAGE_INSTANCE_CREATE,
  STAGE_INSTANCE_DELETE,
  STAGE_INSTANCE_UPDATE,
  SUBSCRIPTION_CREATE,
  SUBSCRIPTION_DELETE,
  SUBSCRIPTION_UPDATE,
  THREAD_CREATE,
  THREAD_DELETE,
  THREAD_LIST_SYNC,
  THREAD_MEMBERS_UPDATE,
  THREAD_MEMBER_UPDATE,
  THREAD_UPDATE,
  TYPING_START,
  USER_UPDATE,
  VOICE_CHANNEL_EFFECT_SEND,
  VOICE_SERVER_UPDATE,
  VOICE_STATE_UPDATE,
  WEBHOOKS_UPDATE,
};
