name: Deprecate package version
description: Deprecates package versions.
inputs:
  package:
    description: Package name
    required: true
  version:
    description: Version to deprecate
    required: true
  message:
    description: Deprecation message
    required: false
    # Default message lives in the command to handle empty strings.
  node-auth-token:
    description: npm authentication token
    required: true
runs:
  using: composite
  steps:
    - name: Deprecate version
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        MESSAGE: ${{ inputs.message || 'This version is deprecated. Please use a newer version.' }}
        PACKAGE: ${{ inputs.package }}
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
      run: |
        pnpm exec npm-deprecate --name "$VERSION" --message "$MESSAGE" --package "$PACKAGE"
