name: Deprecate version
on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true
        type: choice
        options:
          - '@discord-selfbot-sdk/core'
          - '@discord-selfbot-sdk/bot'
          - '@discord-selfbot-sdk/rest'
          - '@discord-selfbot-sdk/util'
          - '@discord-selfbot-sdk/ws'
      version:
        description: Version(s)
        required: true
        type: string
      message:
        description: Deprecation message
        required: false
        type: string
jobs:
  deprecate:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Dijnie'
    steps:
      - name: Install Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Deprecate
        run: npm deprecate "${{ inputs.package }}@${{ inputs.version }}" "${{ inputs.message || 'This version has been deprecated.' }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
