name: Release Tagged Dev
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        default: 'main'
      package:
        description: 'Comma separated list of packages to release'
        required: true
        type: string
      tag:
        description: 'The tag to use, generally a feature name'
        required: true
        type: string
      dry_run:
        description: Perform a dry run?
        type: boolean
        default: false
jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    if: github.repository_owner == 'discordjs'
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.DISCORDJS_APP_ID }}
          private-key: ${{ secrets.DISCORDJS_APP_KEY_RELEASE }}
          permission-contents: write

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref || '' }}

      - name: Install Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmCache

      - name: Build dependencies
        run: pnpm run build

      - name: Release packages
        uses: ./packages/actions/src/releasePackages
        with:
          package: ${{ inputs.package }}
          dry: ${{ inputs.dry_run }}
          dev: true
          tag: ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
