name: Release
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'The published name of a single package to release'
        type: choice
        required: false
        options:
          - all
          - '@discord-selfbot-sdk/bot'
          - '@discord-selfbot-sdk/core'
          - '@discord-selfbot-sdk/rest'
          - '@discord-selfbot-sdk/util'
          - '@discord-selfbot-sdk/ws'
      dry_run:
        description: Perform a dry run?
        type: boolean
        default: false
jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: github.repository_owner == 'Dijnie'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js v24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish (dry run)
        if: ${{ inputs.dry_run }}
        run: |
          if [ "${{ inputs.package }}" = "all" ]; then
            pnpm -r --filter "./packages/*" exec pnpm publish --dry-run --no-git-checks --access public
          else
            pnpm --filter "${{ inputs.package }}" exec pnpm publish --dry-run --no-git-checks --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish
        if: ${{ !inputs.dry_run }}
        run: |
          if [ "${{ inputs.package }}" = "all" ]; then
            pnpm -r --filter "./packages/*" exec pnpm publish --no-git-checks --access public
          else
            pnpm --filter "${{ inputs.package }}" exec pnpm publish --no-git-checks --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
