name: Remove tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to remove
        required: true
        type: string
jobs:
  removal:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Dijnie'
    strategy:
      matrix:
        package:
          - '@discord-selfbot-sdk/core'
          - '@discord-selfbot-sdk/bot'
          - '@discord-selfbot-sdk/rest'
          - '@discord-selfbot-sdk/util'
          - '@discord-selfbot-sdk/ws'
      fail-fast: false
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Remove tag
        run: npm dist-tag rm "${{ matrix.package }}" "${{ inputs.tag }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
